defaults:
  deploy_cmd: gem push *.gem
  before_deploy_cmds:
    - sed -i "" -e "s/\".*/\"$(git tag| sed s/v// | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -1)\"/" lib/sport_ngin_aws_auditor/version.rb
    - git add  lib/slack_messaging/version.rb
    - git commit -m "Version Bump" && git push
    - gem build slack_messaging.gemspec
  after_deploy_cmds:
    - rm *.gem
environments:
  -
    rubygems: {}
