name: Develop
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define Run Variables
      run: echo "::set-env name=BRANCH::$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"

    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Configure System
      run: sudo gem update --system 3.0.8 && sudo gem install bundler

    - name: Install Gems
      run: bundle config set path "vendor/bundle" && bundle install

    - name: Run Rspec Tests
      run: bundle exec rspec
