name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: |
        if [[ ${{ github.REF }} == 'refs/heads'* ]]; then # this is a branch, not a pull request
          echo "BRANCH=$(echo ${{ github.REF }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
        else
          echo "BRANCH=$(echo ${{ github.HEAD_REF }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
        fi

    - run: git checkout ${{ env.BRANCH }}

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - run: bundle exec rspec

    - run: bundle exec rubocop
